apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'

android {
    namespace 'com.example.launcherhtmls'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.launcherhtmls"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86_64"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

chaquopy {
    defaultConfig {
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.browser:browser:1.7.0'
}
